package com.assignment.Nimmap.enums;

import lombok.Getter;

@Getter
public enum MessageCodes {

	FIELD_MANDATORY("FIELD_MANDATORY_01"),
	FIELD_INVALID("FIELD_INVALID_02"),
	FIELD_ALPHANUMERIC("FIELD_ALPHANUMERIC_03"),
	SIZE("FIELD_INVALID_LENGHT"),
	PATTERN("FIELD_DATA_INVALID"),
	MESSAGE("SUCCESS"),
	NOT_FOUND("NOT_FOUND"),
	CHARVALIDATION("CHARACTER_VALIDATION"),
	DIGITS("DIGITS_VALIDATION"),
	EMAIL("INVALID_EMAIL"),
	NotEmpty("NOT_EMPTY"),
	NotNull("NOT_NULL"),
	NotBlank("NOT_BLANK"),
	INTERNAL_ERROR("INTERNAL_ERROR"),
	CONSTRAINTVOILATIONEXCEPTION("CONSTRAINT_VIOLATION_EXCEPTION"),
	JSONPARSEXCEPTION("JSON_PARSE_EXCEPTION"),
	;
	
	
    private String strValue;

    MessageCodes(String strValue) {
        this.strValue = strValue;
    }
}

